### ISSUE TITLE
pnfft missing in pkg-config libs

### ISSUE THREAD

**Issue by fweik** [scafacos/scafacos#20]
I get errors when linking against scafacos with p2nfft enabled because p2nfft depends on symbols from pnfft, but this dependency seems not to be reflected in the package config. 

scafacos, pnfft and pfft was build an installed with

```
./configure --prefix=/usr/local/stow/scafacos && make -j32 && make install
```
and all features.
```
pkg-config --libs scafacos
```
returns

```
-L/usr/local/stow/scafacos/lib64 -L/usr/lib64/mpi/gcc/openmpi/lib64 -L/usr/lib64/gcc/x86_64-suse-linux/4.8 -L/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/lib -L/usr/lib64/gcc/x86_64-suse-linux/4.8/../../.. -L/usr/lib64/mpi/gcc/openmpi/lib64 -L/usr/lib64/gcc/x86_64-suse-linux/4.8 -L/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/lib -L/usr/lib64/gcc/x86_64-suse-linux/4.8/../../.. -lfcs4fortran -lfcs -lfcs_direct -lfcs_ewald -lfcs_fmm -lfcs_memd -lfcs_mmm1d -lfcs_mmm2d -lfcs_p2nfft -lgsl -lgslcblas -lm -lfcs_p3m -lfcs_pepc -lfcs_pp3mg -lfcs_vmg -lboost_system -lboost_filesystem -llapack -lblas -lfcs_wolf -lfcs_near -lfcs_gridsort -lfcs_resort -lfcs_common -lfftw3_mpi -lfftw3 -lmpi_usempi -lmpi_mpifh -lmpi -lgfortran -lm -lgomp -lquadmath -lpthread -lmpi_cxx -lmpi -lstdc++ -lm -lgcc_s -lpthread
```
(no -lpnfft).

The failing linking command is

```
mpic++ -Wall -O3 -o Espresso.install Espresso_install-scriptsdir.o Espresso_install-main.o cuda_workaround.o  -L/usr/local/cuda/lib64 ./.libs/libEspressoTcl.a -L/usr/local/stow/scafacos/lib64 ../core/.libs/libEspresso.a -ltcl8.6 -lcurand -lcublas -lcufft -lcudart -L/usr/lib64/mpi/gcc/openmpi/lib64 -L/usr/lib64/gcc/x86_64-suse-linux/4.8 -L/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/lib -L/usr/lib64/gcc/x86_64-suse-linux/4.8/../../.. /usr/local/stow/scafacos/lib64/libfcs4fortran.a /usr/local/stow/scafacos/lib64/libfcs.a /usr/local/stow/scafacos/lib64/libfcs_direct.a /usr/local/stow/scafacos/lib64/libfcs_ewald.a /usr/local/stow/scafacos/lib64/libfcs_fmm.a /usr/local/stow/scafacos/lib64/libfcs_memd.a /usr/local/stow/scafacos/lib64/libfcs_mmm1d.a /usr/local/stow/scafacos/lib64/libfcs_mmm2d.a /usr/local/stow/scafacos/lib64/libfcs_p2nfft.a -lgsl -lgslcblas /usr/local/stow/scafacos/lib64/libfcs_p3m.a /usr/local/stow/scafacos/lib64/libfcs_pepc.a /usr/local/stow/scafacos/lib64/libfcs_pp3mg.a /usr/local/stow/scafacos/lib64/libfcs_vmg.a -lboost_system -lboost_filesystem -llapack -lblas /usr/local/stow/scafacos/lib64/libfcs_wolf.a /usr/local/stow/scafacos/lib64/libfcs_near.a /usr/local/stow/scafacos/lib64/libfcs_gridsort.a /usr/local/stow/scafacos/lib64/libfcs_resort.a /usr/local/stow/scafacos/lib64/libfcs_common.a -lpfft -lz -lfftw3_mpi -lfftw3 -lmpi_usempi -lmpi_mpifh -lgfortran -lgomp -lquadmath -lmpi_cxx -lmpi -lstdc++ -lm -lgcc_s -lpthread
```
adding -lpnfft fixes the linking.

**Comment by mh0fm4** [comment]
Hi,

I guess you have pfft installed locally? There was a bug that the p[n]fft flags were not added to the pkg-config file if p[n]fft is already installed on the system. I fixed this problem in commit 815c85e61c399d8af1875e1096c55ce162a29816.

**Comment by fweik** [comment]
What do you mean by "installed locally"? How else would I install them?

**Comment by mh0fm4** [comment]
You do not have to have FFTW and P[N]FFT installed. The scafacos package includes their sources and if they are not found on the system, then scafacos builds and uses its own versions of FFTW and P[N]FFT.

**Comment by fweik** [comment]
Are you sure about that? It would not build p2nfft before I installed those libs. Also I can't find the source of P[N]FFT in the scafacos repository.

**Comment by mh0fm4** [comment]
I guess, you have empty directories "lib/common/pfft" and "lib/common/pnfft" in your cloned repository?

These are submodules located in other repositories, so you have to do `git submodule update --init --recursive` (within your cloned scafacos directory) to fetch them. Afterward, please continue with bootstrap.

**Comment by fweik** [comment]
Ah ok I did not realize that. But still should't it work with external pnfft?

**Comment by mh0fm4** [comment]
Yes, it should work with an external PNFFT (as well as FFTW and PFFT).

However, there was a bug preventing that the appropriate linker flags are available with pkg-config (as you reported) if the external P[N]FFT libraries are used. This should now be fixed.
