### ISSUE TITLE
Linking with parameters from pkg-config fails

### ISSUE THREAD

**Issue by fweik** [scafacos/scafacos#22]
Linking with the parameters from pkg-config fails with the current HEAD:
`gcc main.c $(pkg-config --libs scafacos)`
fails with
```
/usr/local/lib64/libfcs_ewald.so: undefined reference to `fcs_get_box_c'
/usr/local/lib64/libfcs_ewald.so: undefined reference to `fcs_get_box_b'
/usr/local/lib64/libfcs_ewald.so: undefined reference to `fcs_result_create'
/usr/local/lib64/libfcs_ewald.so: undefined reference to `fcs_get_box_a'
/usr/local/lib64/libfcs_ewald.so: undefined reference to `fcs_get_periodicity'
/usr/local/lib64/libfcs_ewald.so: undefined reference to `fcs_get_max_local_particles'
/usr/local/lib64/libfcs_ewald.so: undefined reference to `fcs_get_method'
collect2: error: ld returned 1 exit status
```

I did build scafacos with
`./configure --disable-fcs-fortran --with-pic --prefix=/usr/local`
and I think this worked fine in the past. This is probably an issue with the order of the -l parameters.
`pkg-config --libs scafacos` gives
```
-L/usr/local/lib64 -L/usr/lib64/mpi/gcc/openmpi/lib64 -L/usr/lib64/gcc/x86_64-suse-linux/4.8 -L/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/lib -L/usr/lib64/gcc/x86_64-suse-linux/4.8/../../.. -L/usr/lib64/mpi/gcc/openmpi/lib64 -L/usr/lib64/gcc/x86_64-suse-linux/4.8 -L/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/lib -L/usr/lib64/gcc/x86_64-suse-linux/4.8/../../.. -lfcs4fortran -lfcs -lfcs_direct -lfcs_ewald -lfcs_fmm -lfcs_memd -lfcs_mmm1d -lfcs_mmm2d -lfcs_p2nfft -lgsl -lgslcblas -lm -lfcs_p3m -lfcs_pepc -lfcs_pp3mg -lfcs_vmg -lboost_system -lboost_filesystem -llapack -lblas -lfcs_wolf -lfcs_near -lfcs_gridsort -lfcs_resort -lfcs_common -lpnfft -lpfft -lfftw3_mpi -lfftw3 -lmpi_usempi -lmpi_mpifh -lmpi -lgfortran -lm -lgomp -lquadmath -lpthread -lmpi_cxx -lmpi -lstdc++ -lm -lgcc_s -lpthread
```
here. I'm pretty sure that this worked not so long ago, but don't have time to pinpoint the exact revision.
( @RudolfWeeber )

**Comment by mh0fm4** [comment]
The interface in libfcs uses the ewald solver in libfcs_ewald and, thus, the order "-lfcs -lfcs_ewald" should be correct. Unfortunately, the ewald solver has also used some functions (i.e. the missing references) from the interface.

I have moved the problematic ewald parts to the interface (like in all other solvers). The linking problem should now be gone.

**Comment by fweik** [comment]
We switched in the meantime to dynamic linking which makes the problem go away anyhow, at least on Linux. But thank you. FMM does not build with --enable-shared btw.

**Comment by mh0fm4** [comment]
--enable-shared should now be working with all solvers. Please, do "bootstrap" after the update, because there is also a bug in libtool (when using a recent version of gfortran) that is now patched in the generated configure script.

**Comment by fweik** [comment]
Yes, works. Thank you.

**Comment by FrederikHeber** [comment]
We have shared libs enabled now?! Great news.
