### ISSUE TITLE
provide a CMake package configuration file

### ISSUE THREAD

**Issue by KaiSzuttor** [scafacos/scafacos#27]
cmake is the de-facto industry standard. by providing a scafacos.cmake other projects that depend on scafacos could just do ```find_package(scafacos)``` in their cmake file and make use of your library.

**Comment by mh0fm4** [comment]
Thanks for the suggestion. I have added a corresponding cmake package file with commit c9676d9c6fe7c99a6d74cfd5b84b7ec446dae0c8.
