### ISSUE TITLE
A bug report (MMM2D)

### ISSUE THREAD

**Issue by xzhh** [scafacos/scafacos#28]
PATH: ./lib/mmm2d/run.c

The function in line 1634: **static fcs_float dielectric_layers_energy_contribution**
In line 1651 & 1668, the **negative sign** should be **removed** from "a[2]=-d->local_positions[c+2];"
The **correct** expression should be "a[2]=d->local_positions[c+2];". Otherwise, it will calculate a distance from a position (to a particle) to itself, which leads to a zero and contributes as a divisor, but in fact it should calculate between one position and its mirror over the boundary.

The same issue happens to the corresponding function for force contribution: See ln. 1700 & 1720 under **static fcs_float dielectric_layers_energy_contribution** (ln. 1683).

For a reference, see the same code in EspressoMD.

Cheers,
Zhen-Hao Xu, Mainz

**Comment by junghans** [comment]
@rhalver can you have a look at this for https://github.com/espressopp/espressopp/pull/420
