### ISSUE TITLE
Fedora 32 linker issue with LAMMPS and USER-SCAFACOS package on latest master

### ISSUE THREAD

**Issue by akohlmey** [scafacos/scafacos#30]
Now that compilation of the downloaded library completes, I get a linker error when linking the LAMMPS executable. Everything is the same as in issue #29. Running the same compilation on Fedora 31 with the exact same command lines completes and links.
```
Scanning dependencies of target lmp
[100%] Building CXX object CMakeFiles/lmp.dir/home/akohlmey/compile/lammps/src/main.cpp.o
[100%] Linking CXX executable lmp
/usr/bin/ld: scafacos_build-prefix/lib/libfcs_fmm.a(libfcs_fmm_mpiwrap_la-mpi_fmm_sort.o):(.bss+0x0): multiple definition of `fcs_mpi_fmm_sort_front_part'; scafacos_build-prefix/lib/libfcs.a(libfcs_la-fcs_fmm.o):(.bss+0x0): first defined here
/usr/bin/ld: scafacos_build-prefix/lib/libfcs_fmm.a(libfcs_fmm_mpiwrap_la-mpi_fmm_sort.o):(.bss+0x4): multiple definition of `fcs_mpi_fmm_sort_back_part'; scafacos_build-prefix/lib/libfcs.a(libfcs_la-fcs_fmm.o):(.bss+0x4): first defined here
/usr/bin/ld: scafacos_build-prefix/lib/libfcs_fmm.a(libfcs_fmm_mpiwrap_la-mpi_fmm_sort.o):(.bss+0x8): multiple definition of `fcs_mpi_fmm_sort_front_merge_presorted'; scafacos_build-prefix/lib/libfcs.a(libfcs_la-fcs_fmm.o):(.bss+0x8): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/lmp.dir/build.make:133: lmp] Error 1
make[1]: *** [CMakeFiles/Makefile2:703: CMakeFiles/lmp.dir/all] Error 2
```

**Comment by rhalver** [comment]
I will check that, as for me the linking was successful and I was able to run the scafacos examples in Lammps. I will try to reproduce the issue and try to find a solution for it.

**Comment by xzhh** [comment]
The USER-SCA package does not support all methods avail in Scafacos. Try compiling Scafacos again by only activating the method that you want to deal with. In your case, I would suggest to deactivate FMM if you don't need it.

For supported methods, I guess you should see in ./src/USER-SCAFACOS

**Comment by rhalver** [comment]
The FMM package is supported. Therefore a solution for the issue should be found. @akohlmey how did you pass the flag to the Fortran compiler with gfortran 10.x? Is there a possibility to get that code, so that I could try to reproduce the problem from there and compare how you passed the flag to how I did it?

**Comment by akohlmey** [comment]
> The FMM package is supported. Therefore a solution for the issue should be found. @akohlmey how did you pass the flag to the Fortran compiler with gfortran 10.x? Is there a possibility to get that code, so that I could try to reproduce the problem from there and compare how you passed the flag to how I did it?

Passing the flags is integrated into the CMake build process, which has been included into the current master (and latest patch release). Thus the commands to reproduce are the same as before:
```
git clone --depth 1 https://github.com/lammps/lammps.git -b master lammps
singularity pull fedora.sif library://lammps/default/lammps_development:fedora32_mingw
singularity shell fedora.sif
cd lammps
mkdir build-scafacos
cd build-scafacos
cmake -D PKG_USER-SCFACOS=yes -D DOWNLOAD_SCAFACOS=yes ../cmake
make
```

**Comment by akohlmey** [comment]
After some digging around and studying docs and bug reports, I would conclude that this linker issue is something that should be corrected in the source code. The following change seems appropriate:
```
  diff --git a/src/fcs_fmm.c b/src/fcs_fmm.c
  index 37acb67..10bbd10 100644
  --- a/src/fcs_fmm.c
  +++ b/src/fcs_fmm.c
  @@ -430,7 +430,7 @@ FCSResult fcs_fmm_tune(FCS handle, fcs_int local_particles, fcs_float *positions
     return FCS_RESULT_SUCCESS;
   }
   
  -int fcs_mpi_fmm_sort_front_part, fcs_mpi_fmm_sort_back_part, fcs_mpi_fmm_sort_front_merge_presorted;
  +extern int fcs_mpi_fmm_sort_front_part, fcs_mpi_fmm_sort_back_part, fcs_mpi_fmm_sort_front_merge_presorted;
   
   /* internal fmm-specific run function */
   FCSResult fcs_fmm_run(FCS handle, fcs_int local_particles,

```
